#!/usr/bin/env bash

########################################################
###                        Help                      ###
########################################################

HELP='
BEM actions

Usage:

    bem [action]

 Actions:

    make   Assemble bem bundles
    clean  Clean assembled files
'

########################################################
###                     Variables                    ###
########################################################

# Node modules directory
NODE_MODULES_DIR='node_modules'

# Node modules binary directory
NODE_MODULES_BIN_DIR="$NODE_MODULES_DIR/.bin"

# Enb
ENB="$NODE_MODULES_BIN_DIR/enb"

# Borschik
BORSCHIK="$NODE_MODULES_BIN_DIR/borschik"

# Bem directory
BEM_DIR='bem'

# Static directory
STATIC_DIR='public/static'

########################################################
###                      Helpers                     ###
########################################################

#
# Print a title of action
#
# @1 {string} Title
#
printTitle() {
    echo "===> $1"
}

########################################################
###                      Actions                     ###
########################################################

#
# Help
#
help() {
    echo "$HELP"
}

# Assemble bem project
make() {
    removeStaticDir

	# Create bem configs
    printTitle 'Creating bem configs'

	ln -sf "$PWD/$NODE_MODULES_DIR/app-bem-dev/borschik.json" "$PWD/$BEM_DIR/.borschik"

	# Make enb
    printTitle 'Making enb'

	"$ENB" make --no-cache --dir "$BEM_DIR"

	# Freeze links
    printTitle 'Freezing links'

	ln -sf "$PWD/$NODE_MODULES_DIR/app-bem-dev/links.json" "$PWD/$BEM_DIR/links.tmp.json"

	"$BORSCHIK" \
	    -t json \
	    -i "$BEM_DIR/links.tmp.json" \
	    -o "$BEM_DIR/links.json"

	rm -f "$BEM_DIR/links.tmp.json" \
	      "$BEM_DIR/.borschik"
}

# Remove a static directory
removeStaticDir() {
	printTitle 'Removing the static dir'

	rm -rf "$STATIC_DIR"
}

# Clean
clean() {
    removeStaticDir

    # Remove bem configs
	printTitle 'Removing bem configs'

	rm -f "$BEM_DIR/.borschik" \
	      "$BEM_DIR/links.json"

	# Remove temporary files
	printTitle 'Removing temporary files'

	rm -rf "$BEM_DIR/.enb/tmp"
}

########################################################
###                    Call action                   ###
########################################################

case "$1" in
    make|clean)
        "$1"
    ;;
    *)
        help
    ;;
esac

