#!/usr/bin/env bash

########################################################
###                        Help                      ###
########################################################

HELP='
BEM.

Usage:

    bem action

Parameters:

    * action

        BEM actions.

        - make   Assemble bem bundles.
        - clean  Clean assembled files.
'

########################################################
###                     Variables                    ###
########################################################

# Node modules directory
NODE_MODULES_DIR='node_modules'

# Node modules binary directory
NODE_MODULES_BIN_DIR="$NODE_MODULES_DIR/.bin"

# Borschik
BORSCHIK="$NODE_MODULES_BIN_DIR/borschik"

# Bem directory
BEM_RELATIVE_DIR='bem'

########################################################
###                      Helpers                     ###
########################################################

#
# Print a title of action
#
# @1 {string} Title
#
printTitle() {
    echo "===> $1"
}

########################################################
###                      Actions                     ###
########################################################

#
# Help
#
help() {
    echo "$HELP"
}

# Assemble bem project
make() {
    removeStaticDir

    printTitle 'Creating bem configs'

    ln -sf "$PWD/$NODE_MODULES_DIR/app-bem-dev/borschik.json" "$PWD/$BEM_RELATIVE_DIR/.borschik"

    printTitle 'Making enb'

    "$NODE_MODULES_BIN_DIR/enb" make --no-cache --dir "$BEM_RELATIVE_DIR"

    printTitle 'Freezing links'

    ln -sf "$PWD/$NODE_MODULES_DIR/app-bem-dev/links.json" "$PWD/$BEM_RELATIVE_DIR/links.tmp.json"

    "$BORSCHIK" \
        -t json \
        -i "$BEM_RELATIVE_DIR/links.tmp.json" \
        -o "$BEM_RELATIVE_DIR/links.json"

    rm -f "$BEM_RELATIVE_DIR/links.tmp.json" \
          "$BEM_RELATIVE_DIR/.borschik"
}

# Remove a static directory
removeStaticDir() {
    printTitle 'Removing the static dir'

    rm -rf 'public/static'
}

# Clean
clean() {
    removeStaticDir

    printTitle 'Removing bem configs'

    rm -f "$BEM_RELATIVE_DIR/.borschik" \
          "$BEM_RELATIVE_DIR/links.json"

    printTitle 'Removing temporary files'

    rm -rf "$BEM_RELATIVE_DIR/.enb/tmp"
}

########################################################
###                    Call action                   ###
########################################################

case "$1" in
    make|clean)
        "$1"
    ;;
    *)
        help
    ;;
esac

